#
# CI Pipeline Template Configuration
# This chart installs the WorkflowTemplate that defines the CI pipeline steps
#
---
template:
  # Template metadata configuration
  name: "rails-ci-buildkit"
  namespace: "" # Will use the release namespace if empty
  
  # Default workflow parameters
  defaultParameters:
    repo_url: "https://github.com/thamilton-callrail/openapi-ruby-on-rails.git"
    branch: "main"
    dockerfile: "Dockerfile"
    context_path: ""
    image_name: "ghcr.io/thamilton-callrail/openapi-ruby-on-rails"
    test_command: "echo 'Running basic checks...' && ruby --version && bundle --version && echo 'All checks passed! ✅'"
  
  # Volume configuration
  volumes:
    workspace:
      size: "2Gi"
    buildkitCache:
      size: "3Gi"

  # Timeout and cleanup configuration
  timeouts:
    activeDeadlineSeconds: 1800  # 30 minutes
    ttlAfterCompletion: 3600     # Keep for 1 hour
    ttlAfterSuccess: 1800        # Keep successful for 30 min
    ttlAfterFailure: 7200        # Keep failed for 2 hours

  # DAG step configurations
  steps:
    # Token verification step
    verifyToken:
      image: "curlimages/curl:8.4.0"
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"
    
    # Git clone step
    gitClone:
      image: "alpine/git:2.40.1"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
    
    # Security scanning step
    securityScan:
      image: "hadolint/hadolint:v2.12.0-alpine"
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
    
    # BuildKit build step
    buildkitBuild:
      image: "moby/buildkit:v0.12.3-rootless"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        privileged: true
        seccompProfile:
          type: Unconfined
      env:
        - name: BUILDKITD_FLAGS
          value: "--oci-worker-no-process-sandbox"
        - name: DOCKER_CONFIG
          value: "/tmp/.docker"
      readinessProbe:
        exec:
          command: [sh, -c, "buildctl debug workers"]
    
    # Test execution step (uses built image from buildkit)
    runTests:
      # Uses the built image from buildkit step - no separate image needed
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "1"
      env:
        - name: RAILS_ENV
          value: "test"
        - name: RACK_ENV
          value: "test"
      
    # Image tagging step
    tagLatest:
      image: "curlimages/curl:8.4.0"
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"

# GitHub configuration
github:
  username: "thamilton-callrail"
  secretName: "github-token"
