=begin
Base Template API

A simple API template with a health check endpoint

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration[8.0]
  def change
    create_table "health_check_response".pluralize.to_sym, id: false do |t|
      t.string :service
      t.string :postgresql
      t.string :redis
      t.string :status

      t.timestamps
    end

  end
end
