=begin
Base Template API

A simple API template with a health check endpoint

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class HealthCheckResponse < ApplicationRecord

end
